// generated by go run genicons.go; DO NOT EDIT

package icons

var list = []struct {
	name string
	data []byte
}{
	{"Betonski", Betonski},
	{"Bravarski", Bravarski},
	{"Fasaderski", Fasaderski},
	{"Gipsarski", Gipsarski},
	{"Istrazivacki", Istrazivacki},
	{"Izolaterski", Izolaterski},
	{"Kamenorezacki", Kamenorezacki},
	{"Kanalizacija", Kanalizacija},
	{"Keramicarski", Keramicarski},
	{"Kovacki", Kovacki},
	{"Likorezacki", Likorezacki},
	{"Limarski", Limarski},
	{"Livacki", Livacki},
	{"Molerski", Molerski},
	{"Parketarski", Parketarski},
	{"Podopolagacki", Podopolagacki},
	{"Pokrivacki", Pokrivacki},
	{"Pripremni", Pripremni},
	{"Roletnarski", Roletnarski},
	{"Rusenja", Rusenja},
	{"Sanitarije", Sanitarije},
	{"Staklorezacki", Staklorezacki},
	{"Stolarija", Stolarija},
	{"Stolarski", Stolarski},
	{"Suvomontazni", Suvomontazni},
	{"Tapetarski", Tapetarski},
	{"Teracerski", Teracerski},
	{"Tesarski", Tesarski},
	{"Vodovod", Vodovod},
	{"Zemljani", Zemljani},
	{"Zidarski", Zidarski},
}
