// generated by go run genicons.go; DO NOT EDIT

package icons

var list = []struct {
	name string
	data []byte
}{
	{"Suvomontazni", Suvomontazni},
	{"Tapetarski", Tapetarski},
	{"Teracerski", Teracerski},
	{"Tesarski", Tesarski},
	{"Vodovod", Vodovod},
	{"Zemljani", Zemljani},
	{"Zidarski", Zidarski},
}
